### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by codestamp** [nickspell/udacity-IntroToParallelProgramming#1]
Can you clarify how you ran your code commandline on your system? It seems the Udacity IDE is not working.

Thanks
Munesh

**Comment by nickspell** [comment]
Sorry for the very late answer.
I have run it with Visual Studio 2015 by manually setting my Debug and Release configs. In each problem directory you should find the .vcxproj file. I am not a VS expert (it is the only project where I have ever used it), but it should import such config for you when you open the project for such file, then it is up to you to install CUDA and opencv (see the README for the versions I have used)
