### ISSUE TITLE
Where did this course go on Udacity?

### ISSUE THREAD

**Issue by uxduck** [nickspell/udacity-IntroToParallelProgramming#3]
Where did this course go... as with so many other courses on Udacity, its now missing. They had so much good content in the past (which other people made) which they have now removed. You wouldn't expect this with YouTube video.

**Comment by dipps18** [comment]
> Where did this course go... as with so many other courses on Udacity, its now missing. They had so much good content in the past (which other people made) which they have now removed. You wouldn't expect this with YouTube video.

https://classroom.udacity.com/courses/cs344

**Comment by uxduck** [comment]
Nice, thanks @dipps18. 2 years later is better than never. :)
